import { Check, Clock3, FileSearch, IndianRupee } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { AppShell, BottomNav, PrimaryButton, ScreenHeader } from '../components/ui';
import { useExtrasCatalog } from '../state/ExtrasCatalogContext';
import { useExtrasRequests } from '../state/ExtrasRequestContext';

const steps = ['Submitted', 'Under review', 'Quote ready', 'Paid', 'Scheduled'];
export function RequestStatusScreen() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const { cartCount } = useExtrasCatalog(); const { getRequest, makeQuoteReady } = useExtrasRequests(); const request = getRequest(id);
  if (!request) return <AppShell bottomNav={<BottomNav cartCount={cartCount} />}><ScreenHeader title="Request status"/><div className="rounded-card border border-border bg-card p-8 text-center"><h1 className="font-display text-xl font-bold">Request not found</h1><button className="mt-4 text-brand" onClick={() => navigate('/extras')}>Back to Extras</button></div></AppShell>;
  const activeIndex = request.status === 'under_review' ? 1 : request.status === 'quote_ready' ? 2 : request.status === 'quote_accepted' ? 3 : 0;
  return <AppShell bottomNav={<BottomNav cartCount={cartCount} />}><ScreenHeader title="Request status"/><div className="mx-auto max-w-2xl"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-brand text-brandContrast"><Check/></div><div><h1 className="font-display text-2xl font-bold">{request.status === 'quote_ready' ? 'Quote ready' : request.status === 'quote_accepted' ? 'Quote accepted' : 'Request submitted'}</h1><p className="text-sm text-muted">We’ll notify you when your quote is ready.</p></div></div>
    <section className="card-gradient mt-6 rounded-card border border-border p-5"><h2 className="font-display font-bold">Request summary</h2><dl className="mt-4 grid gap-4 text-sm"><div><dt className="text-muted">Request</dt><dd className="mt-1 font-bold">{request.title} × {request.quantity}</dd></div><div><dt className="text-muted">Drop point</dt><dd className="mt-1">{request.dropPoint}</dd></div>{request.maximumBudget ? <div><dt className="text-muted">Maximum budget</dt><dd className="mt-1">₹{request.maximumBudget}</dd></div> : null}</dl></section>
    <section className="mt-6"><h2 className="font-display font-bold">Request status</h2><ol className="mt-4 space-y-0">{steps.map((step, index) => <li key={step} className="relative flex min-h-[68px] gap-4"><div className={`relative z-10 grid h-7 w-7 shrink-0 place-items-center rounded-full border ${index <= activeIndex ? 'border-brand bg-brand text-brandContrast' : 'border-muted bg-bg text-muted'}`}>{index < activeIndex ? <Check size={15}/> : index === 1 ? <FileSearch size={14}/> : index === 2 ? <IndianRupee size={14}/> : <Clock3 size={14}/>}</div>{index < steps.length - 1 ? <span className={`absolute left-[13px] top-7 h-[41px] w-px ${index < activeIndex ? 'bg-brand' : 'bg-muted'}`}/> : null}<div><strong className={index === activeIndex ? 'text-brand' : ''}>{step}</strong>{index === activeIndex ? <p className="mt-1 text-xs text-muted">{step === 'Under review' ? 'We’re checking availability and preparing your quote.' : 'Your next action is ready.'}</p> : null}</div></li>)}</ol></section>
    <section className="rounded-card border border-border bg-card p-4 text-sm"><strong>What happens next?</strong><p className="mt-2 leading-6 text-muted">Our operations team reviews the details and sends a structured, expiring quote. You choose whether to accept it.</p></section>
    {request.status === 'under_review' ? <button type="button" onClick={() => makeQuoteReady(id)} className="mt-5 min-h-tap w-full rounded-button border border-brand font-bold text-brand">Preview quote-ready state</button> : null}{request.status === 'quote_ready' ? <PrimaryButton className="mt-5" onClick={() => navigate(`/extras/requests/${id}/quote`)}>Review quote</PrimaryButton> : null}
  </div></AppShell>;
}
